// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0pnKabMXjT9lcN486mlWCwqJHiuJUeCc',
    appId: '1:824249531144:web:fb608b2eea4f7d333c4abd',
    messagingSenderId: '824249531144',
    projectId: 'sessizsehir-73b29',
    authDomain: 'sessizsehir-73b29.firebaseapp.com',
    storageBucket: 'sessizsehir-73b29.appspot.com',
    measurementId: 'G-G4E0BYNV7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxuov3eNHzfey5RzzJ0xv50mE8xS_TL8w',
    appId: '1:824249531144:android:36d65960a58b6a243c4abd',
    messagingSenderId: '824249531144',
    projectId: 'sessizsehir-73b29',
    storageBucket: 'sessizsehir-73b29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3EBSdbOKt6s4-aCLK9fSnlYVaPTF7qpQ',
    appId: '1:824249531144:ios:35917d5cf1a5ffe93c4abd',
    messagingSenderId: '824249531144',
    projectId: 'sessizsehir-73b29',
    storageBucket: 'sessizsehir-73b29.appspot.com',
    iosBundleId: 'com.example.sesizzSehir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3EBSdbOKt6s4-aCLK9fSnlYVaPTF7qpQ',
    appId: '1:824249531144:ios:7c5d1853f00e6b8a3c4abd',
    messagingSenderId: '824249531144',
    projectId: 'sessizsehir-73b29',
    storageBucket: 'sessizsehir-73b29.appspot.com',
    iosBundleId: 'com.example.sesizzSehir.RunnerTests',
  );
}
